services:
  mysql:
    image: mysql:8.0
    container_name: mysql-emoney
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: emoney
      MYSQL_USER: useremoney
      MYSQL_PASSWORD: Password#123

    ports:
      - "3306:3306"

    volumes:
      - emoney_mysql_data:/var/lib/mysql

volumes:
  emoney_mysql_data: